MAX_TERMINAL_SIZE = 2**16 - 1

TERMINAL_DEFAULT_WIDTH = 80
TERMINAL_DEFAULT_HEIGHT = 24

JUPYTER_DEFAULT_WIDTH = 120
JUPYTER_DEFAULT_HEIGHT = 50

BROWSER_DEFAULT_WIDTH = 160
BROWSER_DEFAULT_HEIGHT = None
