# Data - General

ROOT_KEY = '__root__'
DATA_KEY = 'data'
UNTITLED_KEY = '_untitled'
ASYNC_LOAD_SLEEP_TIME = 0.05

# Data - Display

MAX_TERMINAL_SIZE = 2**16 - 1

TERMINAL_DEFAULT_WIDTH = 80
TERMINAL_DEFAULT_HEIGHT = 24

JUPYTER_DEFAULT_WIDTH = 112
JUPYTER_DEFAULT_HEIGHT = 48

BROWSER_DEFAULT_WIDTH = 160
BROWSER_DEFAULT_HEIGHT = None

PANEL_TITLE_BASE_16_TOKEN = ('Base16', 'Classes')
PANEL_TITLE_GENERAL_TOKEN = ('Name', 'Class')
PANEL_TITLE_EXTRA_STYLE = 'italic not bold not underline'
TABLE_BORDER_BASE_16_TOKEN = ('Base16', 'LineHighlight')
TABLE_BORDER_GENERAL_TOKEN = ('Comment',)
