# Data - General

ROOT_KEY = '__root__'
DATA_KEY = 'data'
UNTITLED_KEY = '_untitled'
ASYNC_LOAD_SLEEP_TIME = 0.05

# Data - Display

MAX_TERMINAL_SIZE = 2**16 - 1

TERMINAL_DEFAULT_WIDTH = 80
TERMINAL_DEFAULT_HEIGHT = 24

JUPYTER_DEFAULT_WIDTH = 112
JUPYTER_DEFAULT_HEIGHT = 48

BROWSER_DEFAULT_WIDTH = 160
BROWSER_DEFAULT_HEIGHT = None

# Data - Display - Panel

TITLE_BLANK_LINES = 1
DOUBLE_LINE_TITLE_HEIGHT = TITLE_BLANK_LINES + 2
SINGLE_LINE_TITLE_HEIGHT = TITLE_BLANK_LINES + 1

MIN_PANEL_LINES_SHOWN_TO_ALLOW_DOUBLE_LINE_TITLE = 8
MIN_PANEL_LINES_SHOWN_TO_ALLOW_SINGLE_LINE_TITLE = 3

PANEL_TITLE_BASE_16_TOKEN = ('Base16', 'Classes')
PANEL_TITLE_GENERAL_TOKEN = ('Name', 'Class')
PANEL_TITLE_EXTRA_STYLE = 'italic not bold not underline'
TABLE_BORDER_BASE_16_TOKEN = ('Base16', 'LineHighlight')
TABLE_BORDER_GENERAL_TOKEN = ('Comment',)

# Data - Display - Styles
STYLE_CLS_NAME_TINTED_BASE16_PREFIX = 'TintedBase16'
STYLE_CLS_NAME_SUFFIX = 'Style'
THEME_KEY_TINTED_BASE16_SUFFIX = '-t16'
PYGMENTS_SUFFIX = '-pygments'
ANSI_PREFIX = 'ansi-'
RANDOM_PREFIX = 'random'
AUTO_VALUE = 'auto'
