# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  apt_packages:
    - language-pack-en
  jobs:
    post_create_environment:
      # Install uv
      # https://docs.astral.sh/uv/
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - echo "$HOME/.local/bin" >> $GITHUB_PATH
    post_install:
      # Install dependencies with 'docs' dependency group
      - uv sync --group docs
      # Generate code documentation skeleton
      - uv run python docs/gen_ref_pages.py
mkdocs:
  configuration: mkdocs.yml
