site_name: "Omnipy"

theme:
  name: "material"

nav:
- Omnipy: index.md
- Code Reference: reference/

plugins:
- search
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    handlers:
      python:
        paths: [ src ]
        options:
          show_root_heading: true
          show_if_no_docstring: true
          show_submodules: true
          show_signature_annotations: true
          separate_signature: true
          inherited_members: true