site_name: Omnipy
theme:
  name: material
  custom_dir: docs/overrides
#  features:
#    - content.code.annotation
#    - navigation.tabs
#    - search.highlight
#    - toc.integrate
  language: en
  palette:
    - scheme: omnipy
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - codehilite
  - extra
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
#  - attr_list
#  - footnotes
#  - md_in_html

nav:
- Omnipy: index.md
- Code Reference: reference/

plugins:
- search
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    handlers:
      python:
        paths: [ src ]
        options:
          show_root_heading: true
          show_if_no_docstring: true
          show_submodules: true
          show_signature_annotations: true
          separate_signature: true
          inherited_members: true