site_name: Omnipy
theme:
  name: material
  custom_dir: docs/overrides
#  features:
#    - content.code.annotation
#    - navigation.tabs
#    - search.highlight
#    - toc.integrate
  language: en
  palette:
    - scheme: omnipy
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - codehilite
  - extra
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

#markdown_extensions:
#  - admonition
#  - attr_list
#  - footnotes
#  - md_in_html
