site_name: Omnipy
repo_url: https://github.com/fairtracks/omnipy
site_url: https://omnipy.readthedocs.io/
theme:
  name: material
  custom_dir: docs/overrides
  language: en
  palette:
    - scheme: omnipy
  features:
    - content.code.annotation
    - navigation.tabs
    - navigation.sections
    - search.highlight
    - toc.integrate
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - codehilite
  - extra
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ["docs"]
  - pymdownx.superfences
  - pymdownx.blocks.html
  - mdx_truly_sane_lists
#  - attr_list
#  - footnotes
#  - md_in_html

nav:
- Omnipy: index.md
- Python typing: python_typing.md
- Data models: data_models.md
- Contributing: contributing.md
- Release notes: release_notes.md
- Code Reference: reference/

watch:
  - src

plugins:
- search
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    handlers:
      python:
        paths: [ src ]
        options:
          filters:
            - "!^_"
            - "^__"
            - "!^__all__"
            - "!^pyd"
          heading_level: 1
          show_root_heading: true
          show_if_no_docstring: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          summary: true
          show_signature_annotations: true
          separate_signature: true
          signature_crossrefs: true
