site_name: Omnipy
site_description: Omnipy is a type-driven Python library for data conversion, parsing and wrangling;
                  tool and web service interoperability; and scalable dataflow orchestration
repo_url: https://github.com/fairtracks/omnipy
site_url: https://omnipy.readthedocs.io/

theme:
  name: material
  custom_dir: docs/overrides
  language: en
  palette:
    - scheme: omnipy
  logo: images/omnipy-puzzle-piece-logo-white.png
  favicon: images/favicon.png
#  icon:
#    annotation: material/arrow-right-circle
  features:
    - content.code.copy
    - content.code.annotation
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.tracking
    - search.highlight
    - toc.integrate
    - toc.follow
extra_css:
  - https://cdn.jsdelivr.net/npm/hack-font@3.3.0/build/web/hack.css
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
markdown_extensions:
#  - pymdownx.details
  - pymdownx.highlight:
      default_lang: python
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      base_path: ["docs"]
  - pymdownx.superfences
  - pymdownx.blocks.html
#  - pymdownx.blocks.tab
  - mdx_truly_sane_lists
  - callouts
#  - attr_list
#  - md_in_html
#  - footnotes

nav:
- Omnipy: index.md
- Python typing: python_typing.md
- Data models: data_models.md
- Contributing: contributing.md
- Release notes: release_notes.md
- Code Reference: reference/

watch:
  - src

plugins:
- search
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- literate-nav:
    nav_file: SUMMARY.md
- section-index
- markdown-exec
- mkdocstrings:
    handlers:
      python:
        paths: [ src ]
        options:
          filters:
            - "!^_"
            - "^__"
            - "!^__all__"
            - "!^pyd"
          heading_level: 1
          show_root_heading: true
          show_if_no_docstring: true
          show_symbol_type_heading: true
          show_symbol_type_toc: true
          summary: true
          show_signature_annotations: true
          separate_signature: true
          signature_crossrefs: true
