# generated by datamodel-codegen:
#   filename:  comment_schema.json
#   timestamp: 2024-02-07T08:09:26+00:00

"""ISA model representing a comment in an investigation."""

from enum import Enum
from typing import Optional

from omnipy.data.model import Model
import omnipy.util.pydantic as pyd


class FieldType(Enum):
    """JSON-LD type labels used for ISA comment entities.

    Attributes:
        Comment: Marks a JSON object as an ISA comment.
    """

    Comment = 'Comment'


class IsaCommentSchema(pyd.BaseModel):
    """Schema for comments attached to ISA objects.

    Attributes:
        name: Comment key or label.
        value: Comment text associated with ``name``.
    """

    class Config:
        """Validation settings for ISA comment schema parsing.

        Attributes:
            extra: Rejects unknown keys in input data.
            use_enum_values: Emits enum members as raw value strings.
        """

        extra = pyd.Extra.forbid
        use_enum_values = True

    field_id: Optional[str] = pyd.Field(None, alias='@id')
    field_context: Optional[str] = pyd.Field(None, alias='@context')
    field_type: Optional[FieldType] = pyd.Field(None, alias='@type')
    name: Optional[str] = None
    value: Optional[str] = None


class IsaCommentModel(Model[IsaCommentSchema]):
    """Omnipy model wrapper for ISA comment entries.

    Wraps :class:`IsaCommentSchema` so comments can be used as nested Omnipy
    models in ISA documents.
    """

    ...
