# generated by datamodel-codegen:
#   filename:  data_schema.json
#   timestamp: 2024-02-07T08:09:26+00:00

"""ISA model representing a data file in an investigation."""

from enum import Enum
from typing import List, Optional

from omnipy.data.model import Model
import omnipy.util.pydantic as pyd

from . import comment_schema


class FieldType(Enum):
    """JSON-LD type labels used for ISA data-file entities.

    Attributes:
        Data: Marks a JSON object as an ISA data file.
    """

    Data = 'Data'


class Type(Enum):
    """Allowed ISA data-file category labels.

    These values follow ISA-JSON controlled vocabulary entries for different
    kinds of data files generated through assay workflows.
    """

    Raw_Data_File = 'Raw Data File'
    Derived_Data_File = 'Derived Data File'
    Image_File = 'Image File'
    Acquisition_Parameter_Data_File = 'Acquisition Parameter Data File'
    Derived_Spectral_Data_File = 'Derived Spectral Data File'
    Protein_Assignment_File = 'Protein Assignment File'
    Raw_Spectral_Data_File = 'Raw Spectral Data File'
    Peptide_Assignment_File = 'Peptide Assignment File'
    Array_Data_File = 'Array Data File'
    Derived_Array_Data_File = 'Derived Array Data File'
    Post_Translational_Modification_Assignment_File = (
        'Post Translational Modification Assignment File')
    Derived_Array_Data_Matrix_File = 'Derived Array Data Matrix File'
    Free_Induction_Decay_Data_File = 'Free Induction Decay Data File'
    Metabolite_Assignment_File = 'Metabolite Assignment File'
    Array_Data_Matrix_File = 'Array Data Matrix File'


class IsaDataSchema(pyd.BaseModel):
    """Schema for a data file entry in an ISA assay.

    Attributes:
        name: Logical or physical filename for the data object.
        type: Controlled category describing the data file kind.
        comments: Optional free-form metadata attached to the file.
    """

    class Config:
        """Validation settings for ISA data-file schema parsing.

        Attributes:
            extra: Rejects keys not declared by the schema.
            use_enum_values: Converts enum members to string values.
        """

        extra = pyd.Extra.forbid
        use_enum_values = True

    field_id: Optional[str] = pyd.Field(None, alias='@id')
    field_context: Optional[str] = pyd.Field(None, alias='@context')
    field_type: Optional[FieldType] = pyd.Field(None, alias='@type')
    name: Optional[str] = None
    type: Optional[Type] = None
    comments: Optional[List[comment_schema.IsaCommentModel]] = None


class IsaDataModel(Model[IsaDataSchema]):
    """Omnipy model wrapper for ISA data-file records.

    Provides Omnipy model semantics for values validated by
    :class:`IsaDataSchema`.
    """

    ...
