# generated by datamodel-codegen:
#   filename:  factor_value_schema.json
#   timestamp: 2024-02-07T08:09:26+00:00

"""ISA model representing a factor value in an investigation.

ISA means Investigation/Study/Assay, and these classes model ISA-JSON JSON-LD payloads.
"""

from enum import Enum
from typing import List, Optional, Union

from omnipy.data.model import Model
import omnipy.util.pydantic as pyd

from . import comment_schema, factor_schema, ontology_annotation_schema


class FieldType(Enum):
    """JSON-LD type labels used for ISA factor-value entities.

    Attributes:
        FactorValue: Marks a JSON object as an ISA factor assignment value.
    """

    FactorValue = 'FactorValue'


class IsaFactorValueSchema(pyd.BaseModel):
    """Schema for values assigned to study factors.

    Attributes:
        category: Factor definition that this value belongs to.
        value: Actual assigned value, either ontology-backed or scalar.
        unit: Unit ontology term for numeric values when applicable.
        comments: Optional comments describing the assignment.
    """

    class Config:
        """Validation settings for ISA factor-value schema parsing.

        Attributes:
            extra: Rejects keys not declared in the schema.
            use_enum_values: Converts enum members to raw value strings.
        """

        extra = pyd.Extra.forbid
        use_enum_values = True

    field_id: Optional[str] = pyd.Field(None, alias='@id')
    field_context: Optional[str] = pyd.Field(None, alias='@context')
    field_type: Optional[FieldType] = pyd.Field(None, alias='@type')
    category: Optional[factor_schema.IsaFactorModel] = None
    value: Optional[Union[ontology_annotation_schema.IsaOntologyReferenceModel, str, float]] = None
    unit: Optional[ontology_annotation_schema.IsaOntologyReferenceModel] = None
    comments: Optional[List[comment_schema.IsaCommentModel]] = None


class IsaFactorValueModel(Model[IsaFactorValueSchema]):
    """Omnipy model wrapper for ISA factor-value assignments.

    Provides Omnipy model behavior around values validated by
    :class:`IsaFactorValueSchema`.
    """

    ...
