# generated by datamodel-codegen:
#   filename:  factor_schema.json
#   timestamp: 2024-02-07T08:09:26+00:00

"""ISA model representing an experimental factor in an investigation.

These generated schemas map ISA-JSON (Investigation/Study/Assay) JSON-LD metadata into
typed Omnipy models.
"""

from enum import Enum
from typing import List, Optional

from omnipy.data.model import Model
import omnipy.util.pydantic as pyd

from . import comment_schema, ontology_annotation_schema


class FieldType(Enum):
    """JSON-LD type labels used for ISA factor entities.

    Attributes:
        Factor: Marks a JSON object as an ISA study factor.
    """

    Factor = 'Factor'


class IsaFactorSchema(pyd.BaseModel):
    """Schema for an experimental factor defined in a study.

    Attributes:
        factorName: Human-readable factor label.
        factorType: Ontology term describing the factor category.
        comments: Optional comments attached to the factor definition.
    """

    class Config:
        """Validation settings for ISA factor schema parsing.

        Attributes:
            extra: Rejects unknown keys in incoming data.
            use_enum_values: Serializes enums as value strings.
        """

        extra = pyd.Extra.forbid
        use_enum_values = True

    field_id: Optional[str] = pyd.Field(None, alias='@id')
    field_context: Optional[str] = pyd.Field(None, alias='@context')
    field_type: Optional[FieldType] = pyd.Field(None, alias='@type')
    factorName: Optional[str] = None
    factorType: Optional[ontology_annotation_schema.IsaOntologyReferenceModel] = None
    comments: Optional[List[comment_schema.IsaCommentModel]] = None


class IsaFactorModel(Model[IsaFactorSchema]):
    """Omnipy model wrapper for ISA study factors.

    Wraps :class:`IsaFactorSchema` for use in Omnipy datasets and nested ISA
    structures.
    """

    ...
