# generated by datamodel-codegen:
#   filename:  investigation_schema.json
#   timestamp: 2024-02-07T08:09:26+00:00

"""ISA model representing an investigation.

ISA denotes Investigation/Study/Assay, and this module maps ISA-JSON JSON-LD
investigation records into Omnipy models.
"""

from datetime import date, datetime
from enum import Enum
from typing import List, Optional, Union

from omnipy.data.model import Model
import omnipy.util.pydantic as pyd

from . import (comment_schema,
               ontology_source_reference_schema,
               person_schema,
               publication_schema,
               study_schema)
from .validators import date_to_iso_format


class FieldType(Enum):
    """JSON-LD type labels used for ISA investigation entities.

    Attributes:
        Investigation: Marks a JSON object as an ISA investigation.
    """

    Investigation = 'Investigation'


class IsaInvestigationSchema(pyd.BaseModel):
    """Schema for an ISA investigation document.

    Attributes:
        identifier: Stable identifier for the investigation.
        title: Human-readable investigation title.
        studies: Study entries included in this investigation.
        submissionDate: Submission date value for the investigation metadata.
        publicReleaseDate: Public release date for the investigation.
    """

    class Config:
        """Validation settings for ISA investigation schema parsing.

        Attributes:
            extra: Rejects undeclared keys in incoming payloads.
            use_enum_values: Emits enum fields as their value strings.
        """

        extra = pyd.Extra.forbid
        use_enum_values = True

    field_id: Optional[str] = pyd.Field(None, alias='@id')
    field_context: Optional[str] = pyd.Field(None, alias='@context')
    field_type: Optional[FieldType] = pyd.Field(None, alias='@type')
    filename: Optional[str] = None
    identifier: Optional[str] = None
    title: Optional[str] = None
    description: Optional[str] = None
    submissionDate: Optional[Union[datetime, date, pyd.constr(max_length=0)]] = None
    publicReleaseDate: Optional[Union[datetime, date, pyd.constr(max_length=0)]] = None
    ontologySourceReferences: Optional[List[
        ontology_source_reference_schema.IsaOntologySourceReferenceModel]] = None
    publications: Optional[List[publication_schema.IsaPublicationModel]] = None
    people: Optional[List[person_schema.IsaPersonModel]] = None
    studies: Optional[List[study_schema.IsaStudyModel]] = None
    comments: Optional[List[comment_schema.IsaCommentModel]] = None

    _date_to_iso_format = pyd.validator(
        'submissionDate', 'publicReleaseDate', allow_reuse=True)(
            date_to_iso_format)


class IsaInvestigationModel(Model[IsaInvestigationSchema]):
    """Omnipy model wrapper for ISA investigation metadata.

    Wraps :class:`IsaInvestigationSchema` so investigations integrate with
    Omnipy dataset and model utilities.
    """

    ...
