# generated by datamodel-codegen:
#   filename:  material_attribute_value_schema.json
#   timestamp: 2024-02-07T08:09:26+00:00

"""ISA model representing a material attribute value in an investigation."""

from enum import Enum
from typing import List, Optional, Union

from omnipy.data.model import Model
import omnipy.util.pydantic as pyd

from . import comment_schema, material_attribute_schema, ontology_annotation_schema


class FieldType(Enum):
    """Enum of JSON-LD type labels for ISA material attribute values."""

    MaterialAttributeValue = 'MaterialAttributeValue'


class IsaMaterialAttributeValueSchema(pyd.BaseModel):
    """Pydantic schema for a material attribute value."""

    class Config:
        """Pydantic configuration for strict ISA material-attribute-value validation."""

        extra = pyd.Extra.forbid
        use_enum_values = True

    field_id: Optional[str] = pyd.Field(None, alias='@id')
    field_context: Optional[str] = pyd.Field(None, alias='@context')
    field_type: Optional[FieldType] = pyd.Field(None, alias='@type')
    category: Optional[material_attribute_schema.IsaMaterialAttributeModel] = None
    value: Optional[Union[ontology_annotation_schema.IsaOntologyReferenceModel, str, float]] = None
    unit: Optional[ontology_annotation_schema.IsaOntologyReferenceModel] = None
    comments: Optional[List[comment_schema.IsaCommentModel]] = None


class IsaMaterialAttributeValueModel(Model[IsaMaterialAttributeValueSchema]):
    """ISA model representing a material attribute value."""

    ...
