# generated by datamodel-codegen:
#   filename:  material_attribute_schema.json
#   timestamp: 2024-02-07T08:09:26+00:00

"""ISA model representing a material attribute category."""

from enum import Enum
from typing import Optional

from omnipy.data.model import Model
import omnipy.util.pydantic as pyd

from . import ontology_annotation_schema


class FieldType(Enum):
    """JSON-LD type labels used for ISA material-attribute entities.

    Attributes:
        MaterialAttribute: Marks a JSON object as an ISA material attribute.
    """

    MaterialAttribute = 'MaterialAttribute'


class IsaMaterialAttributeSchema(pyd.BaseModel):
    """Schema for material attribute categories in ISA.

    Attributes:
        characteristicType: Ontology term describing the attribute category.
    """

    class Config:
        """Validation settings for ISA material-attribute schema parsing.

        Attributes:
            extra: Rejects keys not present in the schema.
            use_enum_values: Serializes enums with raw value strings.
        """

        extra = pyd.Extra.forbid
        use_enum_values = True

    field_id: Optional[str] = pyd.Field(None, alias='@id')
    field_context: Optional[str] = pyd.Field(None, alias='@context')
    field_type: Optional[FieldType] = pyd.Field(None, alias='@type')
    characteristicType: Optional[ontology_annotation_schema.IsaOntologyReferenceModel] = None


class IsaMaterialAttributeModel(Model[IsaMaterialAttributeSchema]):
    """Omnipy model wrapper for ISA material attribute categories.

    Provides Omnipy ``Model`` integration over
    :class:`IsaMaterialAttributeSchema`.
    """

    ...
