# generated by datamodel-codegen:
#   filename:  material_attribute_value_schema.json
#   timestamp: 2024-02-07T08:09:26+00:00
"""ISA model representing a material attribute value in an investigation.

ISA-JSON captures Investigation/Study/Assay metadata as JSON-LD, which these Omnipy
models validate.
"""

from enum import Enum
from typing import List, Optional, Union

from omnipy.data.model import Model
import omnipy.util.pydantic as pyd

from . import comment_schema, material_attribute_schema, ontology_annotation_schema


class FieldType(Enum):
    """JSON-LD type labels used for ISA material-attribute values.

    Attributes:
        MaterialAttributeValue: Marks a JSON object as an ISA attribute value.
    """

    MaterialAttributeValue = 'MaterialAttributeValue'


class IsaMaterialAttributeValueSchema(pyd.BaseModel):
    """Schema for assigned material attribute values.

    Attributes:
        category: Attribute definition that this value belongs to.
        value: Scalar or ontology-backed attribute value.
        unit: Unit ontology term when the value is quantitative.
        comments: Optional comments attached to the value.
    """
    class Config:
        """Validation settings for ISA attribute-value schema parsing.

        Attributes:
            extra: Rejects undeclared keys from input data.
            use_enum_values: Emits enum members as their value strings.
        """

        extra = pyd.Extra.forbid
        use_enum_values = True

    field_id: Optional[str] = pyd.Field(None, alias='@id')
    field_context: Optional[str] = pyd.Field(None, alias='@context')
    field_type: Optional[FieldType] = pyd.Field(None, alias='@type')
    category: Optional[material_attribute_schema.IsaMaterialAttributeModel] = None
    value: Optional[Union[ontology_annotation_schema.IsaOntologyReferenceModel, str, float]] = None
    unit: Optional[ontology_annotation_schema.IsaOntologyReferenceModel] = None
    comments: Optional[List[comment_schema.IsaCommentModel]] = None


class IsaMaterialAttributeValueModel(Model[IsaMaterialAttributeValueSchema]):
    """Omnipy model wrapper for ISA material attribute values.

    Wraps :class:`IsaMaterialAttributeValueSchema` for consistent Omnipy model
    behavior across ISA components.
    """

    ...
