# generated by datamodel-codegen:
#   filename:  ontology_source_reference_schema.json
#   timestamp: 2024-02-07T08:09:26+00:00

"""ISA model representing an ontology source reference."""

from enum import Enum
from typing import List, Optional

from omnipy.data.model import Model
import omnipy.util.pydantic as pyd

from . import comment_schema


class FieldType(Enum):
    """JSON-LD type labels used for ISA ontology-source entities.

    Attributes:
        OntologySourceReference: Marks a JSON object as an ontology source.
    """

    OntologySourceReference = 'OntologySourceReference'


class IsaOntologySourceReferenceSchema(pyd.BaseModel):
    """Schema for ontology source references in ISA metadata.

    Attributes:
        name: Short source name used by ontology term references.
        version: Version string for the ontology source.
        file: Optional URI or file reference for the ontology.
        description: Human-readable source description.
    """

    class Config:
        """Validation settings for ISA ontology-source schema parsing.

        Attributes:
            extra: Rejects undeclared keys in input payloads.
            use_enum_values: Serializes enum values as strings.
        """

        extra = pyd.Extra.forbid
        use_enum_values = True

    field_id: Optional[str] = pyd.Field(None, alias='@id')
    field_context: Optional[str] = pyd.Field(None, alias='@context')
    field_type: Optional[FieldType] = pyd.Field(None, alias='@type')
    comments: Optional[List[comment_schema.IsaCommentModel]] = None
    description: Optional[str] = None
    file: Optional[str] = None
    name: Optional[str] = None
    version: Optional[str] = None


class IsaOntologySourceReferenceModel(Model[IsaOntologySourceReferenceSchema]):
    """Omnipy model wrapper for ISA ontology-source metadata.

    Provides Omnipy ``Model`` behavior for values validated by
    :class:`IsaOntologySourceReferenceSchema`.
    """

    ...
