# generated by datamodel-codegen:
#   filename:  ontology_annotation_schema.json
#   timestamp: 2024-02-07T08:09:26+00:00

"""ISA model representing an ontology annotation in an investigation."""

from enum import Enum
from typing import List, Optional, Union

from omnipy.data.model import Model
import omnipy.util.pydantic as pyd

from . import comment_schema


class FieldType(Enum):
    """JSON-LD type labels used for ISA ontology-annotation entities.

    Attributes:
        OntologyAnnotation: Marks a JSON object as an ontology annotation.
    """

    OntologyAnnotation = 'OntologyAnnotation'


class IsaOntologyReferenceSchema(pyd.BaseModel):
    """Schema for ontology terms referenced in ISA metadata.

    Attributes:
        annotationValue: Free-text or numeric value associated with the term.
        termSource: Short name of the ontology source.
        termAccession: Accession identifier for the ontology term.
        comments: Optional comments attached to the annotation.
    """

    class Config:
        """Validation settings for ISA ontology-annotation parsing.

        Attributes:
            extra: Rejects keys that are not defined by the schema.
            use_enum_values: Outputs enum fields as value strings.
        """

        extra = pyd.Extra.forbid
        use_enum_values = True

    field_id: Optional[str] = pyd.Field(None, alias='@id')
    field_context: Optional[str] = pyd.Field(None, alias='@context')
    field_type: Optional[FieldType] = pyd.Field(None, alias='@type')
    annotationValue: Optional[Union[str, float]] = None
    termSource: Optional[str] = pyd.Field(
        None,
        description='The abbreviated ontology name. It should correspond to one of the sources as '
        'specified in the ontologySourceReference section of the Investigation.',
    )
    termAccession: Optional[str] = None
    comments: Optional[List[comment_schema.IsaCommentModel]] = None


class IsaOntologyReferenceModel(Model[IsaOntologyReferenceSchema]):
    """Omnipy model wrapper for ISA ontology annotations.

    Wraps :class:`IsaOntologyReferenceSchema` for typed integration in ISA
    model graphs.
    """

    ...
