# generated by datamodel-codegen:
#   filename:  organization_schema.json
#   timestamp: 2024-02-07T08:09:26+00:00

"""ISA model representing an organization in an investigation."""

from enum import Enum
from typing import Optional

from omnipy.data.model import Model
import omnipy.util.pydantic as pyd


class FieldType(Enum):
    """JSON-LD type labels used for ISA organization entities.

    Attributes:
        Organization: Marks a JSON object as an ISA organization.
    """

    Organization = 'Organization'


class IsaOrganizationSchema(pyd.BaseModel):
    """Schema for organization entries referenced in ISA metadata.

    Attributes:
        name: Organization name.
    """

    class Config:
        """Validation settings for ISA organization schema parsing.

        Attributes:
            extra: Rejects unknown keys.
            use_enum_values: Emits enum members as value strings.
        """

        extra = pyd.Extra.forbid
        use_enum_values = True

    field_id: Optional[str] = pyd.Field(None, alias='@id')
    field_context: Optional[str] = pyd.Field(None, alias='@context')
    field_type: Optional[FieldType] = pyd.Field(None, alias='@type')
    name: Optional[str] = None


class IsaOrganizationModel(Model[IsaOrganizationSchema]):
    """Omnipy model wrapper for ISA organization entries.

    Wraps :class:`IsaOrganizationSchema` so organizations can be embedded as
    typed ISA model values.
    """

    ...
