# generated by datamodel-codegen:
#   filename:  person_schema.json
#   timestamp: 2024-02-07T08:09:26+00:00

from enum import Enum
from typing import List, Optional

from omnipy.data.model import Model
import omnipy.util._pydantic as pyd

from . import comment_schema, ontology_annotation_schema


class FieldType(Enum):
    Person = 'Person'


class IsaPersonSchema(pyd.BaseModel):
    class Config:
        extra = pyd.Extra.forbid
        use_enum_values = True

    field_id: Optional[str] = pyd.Field(None, alias='@id')
    field_context: Optional[str] = pyd.Field(None, alias='@context')
    field_type: Optional[FieldType] = pyd.Field(None, alias='@type')
    lastName: Optional[str] = None
    firstName: Optional[str] = None
    midInitials: Optional[str] = None
    email: Optional[pyd.EmailStr] = None
    phone: Optional[str] = None
    fax: Optional[str] = None
    address: Optional[str] = None
    affiliation: Optional[str] = None
    roles: Optional[List[ontology_annotation_schema.IsaOntologyReferenceModel]] = None
    comments: Optional[List[comment_schema.IsaCommentModel]] = None


class IsaPersonModel(Model[IsaPersonSchema]):
    ...
