# generated by datamodel-codegen:
#   filename:  person_schema.json
#   timestamp: 2024-02-07T08:09:26+00:00
"""ISA model representing a person in an investigation.

ISA denotes Investigation/Study/Assay metadata, represented here through ISA-JSON
JSON-LD schema models.
"""

from enum import Enum
from typing import List, Optional

from omnipy.data.model import Model
import omnipy.util.pydantic as pyd

from . import comment_schema, ontology_annotation_schema


class FieldType(Enum):
    """JSON-LD type labels used for ISA person entities.

    Attributes:
        Person: Marks a JSON object as an ISA person record.
    """

    Person = 'Person'


class IsaPersonSchema(pyd.BaseModel):
    """Schema for people associated with ISA investigations.

    Attributes:
        firstName: Given name.
        lastName: Family name.
        email: Contact email for the person.
        affiliation: Organizational affiliation text.
        roles: Ontology terms describing investigation roles.
    """
    class Config:
        """Validation settings for ISA person schema parsing.

        Attributes:
            extra: Rejects keys not listed in the schema.
            use_enum_values: Converts enum members to raw strings.
        """

        extra = pyd.Extra.forbid
        use_enum_values = True

    field_id: Optional[str] = pyd.Field(None, alias='@id')
    field_context: Optional[str] = pyd.Field(None, alias='@context')
    field_type: Optional[FieldType] = pyd.Field(None, alias='@type')
    lastName: Optional[str] = None
    firstName: Optional[str] = None
    midInitials: Optional[str] = None
    email: Optional[pyd.EmailStr] = None
    phone: Optional[str] = None
    fax: Optional[str] = None
    address: Optional[str] = None
    affiliation: Optional[str] = None
    roles: Optional[List[ontology_annotation_schema.IsaOntologyReferenceModel]] = None
    comments: Optional[List[comment_schema.IsaCommentModel]] = None


class IsaPersonModel(Model[IsaPersonSchema]):
    """Omnipy model wrapper for ISA person records.

    Wraps :class:`IsaPersonSchema` so people can be validated and nested as
    Omnipy model values.
    """

    ...
