# generated by datamodel-codegen:
#   filename:  process_parameter_value_schema.json
#   timestamp: 2024-02-07T08:09:26+00:00

"""ISA model representing a process parameter value in an investigation."""

from enum import Enum
from typing import List, Optional, Union

from omnipy.data.model import Model
import omnipy.util.pydantic as pyd

from . import comment_schema, ontology_annotation_schema, protocol_parameter_schema


class FieldType(Enum):
    """JSON-LD type labels used for ISA process parameter values.

    Attributes:
        ParameterValue: Marks a JSON object as an ISA process parameter value.
    """

    ParameterValue = 'ParameterValue'


class IsaProcessParameterValueSchema(pyd.BaseModel):
    """Schema for protocol parameter values applied in process steps.

    Attributes:
        category: Protocol parameter definition this value belongs to.
        value: Scalar or ontology-backed assigned value.
        unit: Unit ontology annotation for quantitative values.
        comments: Optional comments attached to the value.
    """

    class Config:
        """Validation settings for ISA process-parameter schema parsing.

        Attributes:
            extra: Rejects unknown keys in input payloads.
            use_enum_values: Emits enum members by value string.
        """

        extra = pyd.Extra.forbid
        use_enum_values = True

    field_id: Optional[str] = pyd.Field(None, alias='@id')
    field_context: Optional[str] = pyd.Field(None, alias='@context')
    field_type: Optional[FieldType] = pyd.Field(None, alias='@type')
    category: Optional[protocol_parameter_schema.IsaProtocolParameterModel] = None
    value: Optional[Union[ontology_annotation_schema.IsaOntologyReferenceModel, str, float]] = None
    unit: Optional[ontology_annotation_schema.IsaOntologyReferenceModel] = None
    comments: Optional[List[comment_schema.IsaCommentModel]] = None


class IsaProcessParameterValueModel(Model[IsaProcessParameterValueSchema]):
    """Omnipy model wrapper for ISA process parameter values.

    Wraps :class:`IsaProcessParameterValueSchema` for typed use in ISA process
    model structures.
    """

    ...
