# generated by datamodel-codegen:
#   filename:  protocol_schema.json
#   timestamp: 2024-02-07T08:09:26+00:00

"""ISA model representing a protocol in an investigation."""

from enum import Enum
from typing import List, Optional

from omnipy.data.model import Model
import omnipy.util.pydantic as pyd

from . import comment_schema, ontology_annotation_schema, protocol_parameter_schema


class Component(pyd.BaseModel):
    """Schema for reusable components declared inside a protocol.

    Attributes:
        componentName: Name of the protocol component.
        componentType: Ontology term describing the component type.
        comments: Optional comments attached to the component.
    """

    componentName: Optional[str] = None
    componentType: Optional[ontology_annotation_schema.IsaOntologyReferenceModel] = (None)
    comments: Optional[List[comment_schema.IsaCommentModel]] = None


class FieldType(Enum):
    """JSON-LD type labels used for ISA protocol entities.

    Attributes:
        Protocol: Marks a JSON object as an ISA protocol.
    """

    Protocol = 'Protocol'


class IsaProtocolSchema(pyd.BaseModel):
    """Schema for protocols referenced by ISA process workflows.

    Attributes:
        name: Protocol name.
        protocolType: Ontology term describing protocol category.
        description: Human-readable protocol description.
        parameters: Parameter definitions accepted by the protocol.
        components: Reusable protocol components and materials.
    """

    class Config:
        """Validation settings for ISA protocol schema parsing.

        Attributes:
            extra: Rejects keys that are not defined in the schema.
            use_enum_values: Serializes enum members by value.
        """

        extra = pyd.Extra.forbid
        use_enum_values = True

    field_id: Optional[str] = pyd.Field(None, alias='@id')
    field_context: Optional[str] = pyd.Field(None, alias='@context')
    field_type: Optional[FieldType] = pyd.Field(None, alias='@type')
    name: Optional[str] = None
    protocolType: Optional[ontology_annotation_schema.IsaOntologyReferenceModel] = None
    description: Optional[str] = None
    uri: Optional[str] = None
    version: Optional[str] = None
    parameters: Optional[List[protocol_parameter_schema.IsaProtocolParameterModel]] = (None)
    components: Optional[List[Component]] = None
    comments: Optional[List[comment_schema.IsaCommentModel]] = None


class IsaProtocolModel(Model[IsaProtocolSchema]):
    """Omnipy model wrapper for ISA protocol definitions.

    Wraps :class:`IsaProtocolSchema` for typed, validated protocol objects in
    Omnipy ISA datasets.
    """

    ...
