# generated by datamodel-codegen:
#   filename:  protocol_parameter_schema.json
#   timestamp: 2024-02-07T08:09:26+00:00

"""ISA model representing a protocol parameter in an investigation."""

from enum import Enum
from typing import List, Optional

from omnipy.data.model import Model
import omnipy.util.pydantic as pyd

from . import comment_schema, ontology_annotation_schema


class FieldType(Enum):
    """JSON-LD type labels used for ISA protocol-parameter entities.

    Attributes:
        ProtocolParameter: Marks a JSON object as a protocol parameter.
    """

    ProtocolParameter = 'ProtocolParameter'


class IsaProtocolParameterSchema(pyd.BaseModel):
    """Schema for protocol parameters used by ISA process steps.

    Attributes:
        parameterName: Ontology-backed name of the protocol parameter.
        comments: Optional comments attached to the parameter definition.
    """

    class Config:
        """Validation settings for ISA protocol-parameter schema parsing.

        Attributes:
            extra: Rejects undeclared keys from input data.
            use_enum_values: Emits enum fields as their value strings.
        """

        extra = pyd.Extra.forbid
        use_enum_values = True

    field_id: Optional[str] = pyd.Field(None, alias='@id')
    field_context: Optional[str] = pyd.Field(None, alias='@context')
    field_type: Optional[FieldType] = pyd.Field(None, alias='@type')
    parameterName: Optional[ontology_annotation_schema.IsaOntologyReferenceModel] = (None)
    comments: Optional[List[comment_schema.IsaCommentModel]] = None


class IsaProtocolParameterModel(Model[IsaProtocolParameterSchema]):
    """Omnipy model wrapper for ISA protocol parameters.

    Wraps :class:`IsaProtocolParameterSchema` for typed, validated use in ISA
    protocol and process structures.
    """

    ...
