# generated by datamodel-codegen:
#   filename:  publication_schema.json
#   timestamp: 2024-02-07T08:09:26+00:00

"""ISA model representing a publication in an investigation.

ISA-JSON is the JSON-LD representation of Investigation/Study/Assay metadata used by
these generated model types.
"""

from enum import Enum
from typing import List, Optional

from omnipy.data.model import Model
import omnipy.util.pydantic as pyd

from . import comment_schema, ontology_annotation_schema


class FieldType(Enum):
    """JSON-LD type labels used for ISA publication entities.

    Attributes:
        Publication: Marks a JSON object as an ISA publication.
    """

    Publication = 'Publication'


class IsaPublicationSchema(pyd.BaseModel):
    """Schema for publication metadata linked to ISA investigations.

    Attributes:
        pubMedID: PubMed identifier, when available.
        doi: DOI string for the publication.
        authorList: Free-form list of publication authors.
        title: Publication title.
        status: Ontology term describing publication status.
    """

    class Config:
        """Validation settings for ISA publication schema parsing.

        Attributes:
            extra: Rejects undeclared keys from payloads.
            use_enum_values: Emits enum fields as value strings.
        """

        extra = pyd.Extra.forbid
        use_enum_values = True

    field_id: Optional[str] = pyd.Field(None, alias='@id')
    field_context: Optional[str] = pyd.Field(None, alias='@context')
    field_type: Optional[FieldType] = pyd.Field(None, alias='@type')
    pubMedID: Optional[str] = None
    doi: Optional[str] = None
    authorList: Optional[str] = None
    title: Optional[str] = None
    status: Optional[ontology_annotation_schema.IsaOntologyReferenceModel] = None
    comments: Optional[List[comment_schema.IsaCommentModel]] = None


class IsaPublicationModel(Model[IsaPublicationSchema]):
    """Omnipy model wrapper for ISA publication entries.

    Provides Omnipy ``Model`` integration around
    :class:`IsaPublicationSchema`.
    """

    ...
