# generated by datamodel-codegen:
#   filename:  sample_schema.json
#   timestamp: 2024-02-07T08:09:26+00:00

"""ISA model representing a sample in an investigation."""

from enum import Enum
from typing import List, Optional

from omnipy.data.model import Model
import omnipy.util.pydantic as pyd

from . import comment_schema, factor_value_schema, material_attribute_value_schema, source_schema


class FieldType(Enum):
    """JSON-LD type labels used for ISA sample entities.

    Attributes:
        Sample: Marks a JSON object as an ISA sample.
    """

    Sample = 'Sample'


class IsaSampleSchema(pyd.BaseModel):
    """Schema for sample entities in ISA study materials.

    Attributes:
        name: Sample name or identifier.
        characteristics: Material attribute values describing the sample.
        factorValues: Factor assignments associated with the sample.
        derivesFrom: Source materials from which the sample originates.
        comments: Optional comments attached to the sample.
    """

    class Config:
        """Validation settings for ISA sample schema parsing.

        Attributes:
            extra: Rejects unknown keys in input payloads.
            use_enum_values: Serializes enums to their raw values.
        """

        extra = pyd.Extra.forbid
        use_enum_values = True

    field_id: Optional[str] = pyd.Field(None, alias='@id')
    field_context: Optional[str] = pyd.Field(None, alias='@context')
    field_type: Optional[FieldType] = pyd.Field(None, alias='@type')
    name: Optional[str] = None
    characteristics: Optional[List[
        material_attribute_value_schema.IsaMaterialAttributeValueModel]] = None
    factorValues: Optional[List[factor_value_schema.IsaFactorValueModel]] = None
    derivesFrom: Optional[List[source_schema.IsaSourceModel]] = None
    comments: Optional[List[comment_schema.IsaCommentModel]] = None


class IsaSampleModel(Model[IsaSampleSchema]):
    """Omnipy model wrapper for ISA sample records.

    Wraps :class:`IsaSampleSchema` so sample entries can be validated and
    handled consistently across ISA workflows.
    """

    ...
