# generated by datamodel-codegen:
#   filename:  source_schema.json
#   timestamp: 2024-02-07T08:09:26+00:00

"""ISA model representing a source in an investigation."""

from enum import Enum
from typing import List, Optional

from omnipy.data.model import Model
import omnipy.util.pydantic as pyd

from . import comment_schema, material_attribute_value_schema


class FieldType(Enum):
    """JSON-LD type labels used for ISA source entities.

    Attributes:
        Source: Marks a JSON object as an ISA source.
    """

    Source = 'Source'


class IsaSourceSchema(pyd.BaseModel):
    """Schema for source materials in ISA study definitions.

    Attributes:
        name: Source name or identifier.
        characteristics: Material attribute values describing the source.
        comments: Optional comments attached to the source entry.
    """

    class Config:
        """Validation settings for ISA source schema parsing.

        Attributes:
            extra: Rejects undeclared keys in payloads.
            use_enum_values: Serializes enum members to value strings.
        """

        extra = pyd.Extra.forbid
        use_enum_values = True
        use_enum_values = True

    field_id: Optional[str] = pyd.Field(None, alias='@id')
    field_context: Optional[str] = pyd.Field(None, alias='@context')
    field_type: Optional[FieldType] = pyd.Field(None, alias='@type')
    name: Optional[str] = None
    characteristics: Optional[List[
        material_attribute_value_schema.IsaMaterialAttributeValueModel]] = None
    comments: Optional[List[comment_schema.IsaCommentModel]] = None


class IsaSourceModel(Model[IsaSourceSchema]):
    """Omnipy model wrapper for ISA source records.

    Provides Omnipy model behavior on top of
    :class:`IsaSourceSchema` validation.
    """

    ...
