# generated by datamodel-codegen:
#   filename:  source_schema.json
#   timestamp: 2024-02-07T08:09:26+00:00

"""ISA model representing a source in an investigation."""

from enum import Enum
from typing import List, Optional

from omnipy.data.model import Model
import omnipy.util.pydantic as pyd

from . import comment_schema, material_attribute_value_schema


class FieldType(Enum):
    """Enum of JSON-LD type labels for ISA sources."""

    Source = 'Source'


class IsaSourceSchema(pyd.BaseModel):
    """Pydantic schema for a source material in a study."""

    class Config:
        """Pydantic configuration for strict ISA source validation."""

        extra = pyd.Extra.forbid
        use_enum_values = True
        use_enum_values = True

    field_id: Optional[str] = pyd.Field(None, alias='@id')
    field_context: Optional[str] = pyd.Field(None, alias='@context')
    field_type: Optional[FieldType] = pyd.Field(None, alias='@type')
    name: Optional[str] = None
    characteristics: Optional[List[
        material_attribute_value_schema.IsaMaterialAttributeValueModel]] = None
    comments: Optional[List[comment_schema.IsaCommentModel]] = None


class IsaSourceModel(Model[IsaSourceSchema]):
    """ISA model representing a study source material."""

    ...
