# generated by datamodel-codegen:
#   filename:  study_group.json
#   timestamp: 2024-02-07T08:09:26+00:00

"""ISA model representing a study group in an investigation."""

from enum import Enum
from typing import List, Optional

from omnipy.data.model import Model
import omnipy.util.pydantic as pyd

from . import comment_schema, factor_value_schema, sample_schema


class FieldType(Enum):
    """JSON-LD type labels used for ISA study-group entities.

    Attributes:
        Study_Group: Marks a JSON object as an ISA study group.
    """

    Study_Group = 'Study Group'


class IsaStudyGroupSchema(pyd.BaseModel):
    """Schema for study groups used to organize related samples.

    Attributes:
        name: Study group label.
        factor_levels: Factor-value assignments that define the group.
        study_group_size: Number of members in the group.
        members: Sample entries assigned to the group.
    """

    class Config:
        """Validation settings for ISA study-group schema parsing.

        Attributes:
            extra: Rejects keys not declared by the schema.
            use_enum_values: Converts enum members to value strings.
        """

        extra = pyd.Extra.forbid
        use_enum_values = True

    field_id: Optional[str] = pyd.Field(None, alias='@id')
    field_context: Optional[str] = pyd.Field(None, alias='@context')
    field_type: Optional[FieldType] = pyd.Field(None, alias='@type')
    name: Optional[str] = None
    factor_levels: Optional[List[factor_value_schema.IsaFactorValueModel]] = None
    study_group_size: Optional[int] = None
    members: Optional[List[sample_schema.IsaSampleModel]] = None
    comments: Optional[List[comment_schema.IsaCommentModel]] = None


class IsaStudyGroupModel(Model[IsaStudyGroupSchema]):
    """Omnipy model wrapper for ISA study-group records.

    Wraps :class:`IsaStudyGroupSchema` for validated use in Omnipy ISA
    datasets and related metadata structures.
    """

    ...
